#!/bin/bash

#pip install https://github.com/jupyterhub/nbserverproxy/archive/master.zip
pip install https://github.com/betatim/nbserverproxy/archive/fix-syncthing.zip
jupyter serverextension enable --py nbserverproxy

cd /tmp
wget -O syncthing.tar.gz https://github.com/syncthing/syncthing/releases/download/v1.2.2/syncthing-linux-amd64-v1.2.2.tar.gz

mkdir /tmp/syncthing
tar xzf syncthing.tar.gz -C /tmp/syncthing
